Repository sitamadex11/CovidHelp, pull requests merged in 2021-10, with the labels that each got.

#11 Login screen UI update
  Extension Features/extention1.kt
Labels: Hacktoberfest, UI, hacktoberest-accepted

#8 All the hardcoded strings have been extracted as string resource
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  app/src/main/res/layout/activity_choose.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/activity_vaccine_status.xml
  app/src/main/res/layout/custom_dialog_item.xml
  app/src/main/res/layout/custom_dialog_layout_wb.xml
  app/src/main/res/layout/dialog_email.xml
  app/src/main/res/layout/dialog_message.xml
  app/src/main/res/layout/donation_list_activity.xml
  app/src/main/res/layout/donation_list_item.xml
  app/src/main/res/layout/dropdown_item.xml
  app/src/main/res/layout/edit_profile.xml
  app/src/main/res/layout/fragment_about_us.xml
  app/src/main/res/layout/fragment_add_volunteer.xml
  app/src/main/res/layout/fragment_city_wise.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_other.xml
  app/src/main/res/layout/fragment_view_volunteer.xml
  app/src/main/res/layout/fragment_west_bengal.xml
  app/src/main/res/layout/glass_signup_page.xml
  app/src/main/res/layout/nav_header_layout.xml
  app/src/main/res/layout/network_check_dialog.xml
  app/src/main/res/layout/vaccine_center_listitem.xml
  app/src/main/res/layout/volunteer_list_item.xml
  app/src/main/res/menu/bottom_navigation.xml
  app/src/main/res/menu/fab_menu.xml
  app/src/main/res/menu/navigation_menu.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: good first issue, Hacktoberfest, hacktoberest-accepted

#13 Extension file updated
  Extension Features/extention2.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#16 Updated Extension 3
  Extension Features/extention3.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#17 Updated Extension 4
  Extension Features/extention4.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#18 Fix: UI cleanup of the covid tracker activity to make the state selection spanner visible
  .idea/misc.xml
  app/src/main/res/drawable/dropdownwhite.xml
  app/src/main/res/drawable/spanner.xml
  app/src/main/res/layout/covid_tracker_activity.xml
Labels: enhancement, Hacktoberfest, UI, hacktoberest-accepted

#21 Replace need help with covid help on splash screen
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/values/strings.xml
Labels: Hacktoberfest, UI, hacktoberest-accepted

#32 extention5.kt created
  Extension Features/extention5.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#40 Create extention9.kt
  Extension Features/extention9.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#43 Create extension12.kt
  Extension Features/extension12.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#46 created extension 13 file
  Extension Features/Extension13.kt
Labels: documentation, help wanted, Hacktoberfest, hacktoberest-accepted

#48 Extension 14
  Extension Features/Extension14.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#49 Extension 15
  Extension Features/extension15.kt
Labels: documentation, Hacktoberfest, hacktoberest-accepted

#54 Add a Privacy Policy section in the Nav drawer and load a WebView
  app/src/main/java/com/sitamadex11/CovidHelp/activity/ChooseActivity.kt
  app/src/main/java/com/sitamadex11/CovidHelp/fragments/PrivacyPolicyFragment.kt
  app/src/main/java/com/sitamadex11/CovidHelp/util/Constants.kt
  app/src/main/res/drawable/ic_privacy_policy_24.xml
  app/src/main/res/layout/fragment_privacy_policy.xml
  app/src/main/res/menu/navigation_menu.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Hacktoberfest, hacktoberest-accepted

#55 Update the View Profile UI
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  app/src/main/res/drawable/ic_address.xml
  app/src/main/res/drawable/ic_baseline_edit_24.xml
  app/src/main/res/drawable/ic_baseline_local_phone_24.xml
  app/src/main/res/drawable/ic_district.xml
  app/src/main/res/drawable/ic_state.xml
  app/src/main/res/drawable/view_profile_bg.xml
  app/src/main/res/font/poppins_semibold.ttf
  app/src/main/res/font/product_sans_regular.ttf
  app/src/main/res/layout/fragment_view_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Hacktoberfest, UI, hacktoberest-accepted, UI-Update

#56 change the text .
  .idea/misc.xml
  app/build.gradle
  app/src/main/res/layout/fragment_west_bengal.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Hacktoberfest, UI, hacktoberest-accepted

#58 Add animation to Splash Screen
  .idea/misc.xml
  app/build.gradle
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/raw/covid19_animation.json
  app/src/main/res/values/strings.xml
Labels: Hacktoberfest, UI, hacktoberest-accepted, UI-Update

#64 closing keyboard when clicked in background
  app/src/main/java/com/sitamadex11/CovidHelp/activity/LoginActivity.kt
  app/src/main/java/com/sitamadex11/CovidHelp/activity/VolunteerActivity.kt
Labels: bug, Hacktoberfest, hacktoberest-accepted

#72 adding custom icon from eye-icon(default) for hide-show password in login/signup activity
  .idea/misc.xml
  app/src/main/res/drawable/glass_background_png.png
  app/src/main/res/drawable/ic_baseline_local_phone_24.xml
  app/src/main/res/drawable/ic_baseline_visibility_24.xml
  app/src/main/res/drawable/ic_baseline_visibility_off_24.xml
  app/src/main/res/drawable/ic_show_password_selector.xml
  app/src/main/res/layout/glass_signup_page.xml
Labels: Hacktoberfest, UI, hacktoberest-accepted, UI-Update, New Feature

#76 messages to volunteers directly from the app
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sitamadex11/CovidHelp/fragments/ViewVolunteerFragment.kt
Labels: Hacktoberfest, UI, hacktoberest-accepted, UI-Update
